### ISSUE TITLE
Not able to explore backup from Service Fabric 7.1.428.9590

### ISSUE THREAD

**Issue by mfmadsen** [microsoft/service-fabric-backup-explorer#26]
When trying to start the RestServer targetting a backup made from a cluster running SF 7.1.428.9590, I get the below crash report in EventViewer. My guess is that this is caused by the RestServer having references to Microsoft.ServiceFabric.Data.Impl, Version=6.0.0.0 - or is it something else?
I have tried cloning this repo to update the dependencies to use a newer SF version, but I could not get that to work. I can share the backup if required for your troubleshooting.

Application: Microsoft.ServiceFabric.ReliableCollectionBackup.RestServer.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: c33d3710-2481-422c-a42d-7741b7db02ea@973353755@fabric:/StateManager: Below type used in Reliable Collection urn:settingsDictionary/dataStore could not be loaded. This commonly indicates that the user application is not backwards/forwards compatible. Common compatibility bugs that lead to this error are adding a new type or changing an assembly name without two phase upgrade, or removing a type. If this was caused by user's backwards/forwards compatibility bug, one way to mitigate the issue is to force the upgrade through without safety checks.\r\n\r\nSystem.Fabric.Store.TStore`5[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.ServiceFabric.Data.Collections.DefaultComparer`1[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.ServiceFabric.Data.Impl, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35],[Microsoft.ServiceFabric.Data.Collections.DefaultEqualityComparer`1[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.ServiceFabric.Data.Impl, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35],[Microsoft.ServiceFabric.Data.Collections.EmptyRangePartitioner`1[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.ServiceFabric.Data.Impl, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], Microsoft.ServiceFabric.Data.Impl, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
Stack:
   at System.Environment.FailFast(System.String)
   at Microsoft.ServiceFabric.Replicator.Utility.FailFast(System.String)
   at Microsoft.ServiceFabric.Replicator.ReplicationMetadata.Deserialize(Microsoft.ServiceFabric.Replicator.InMemoryBinaryReader, Microsoft.ServiceFabric.Replicator.InMemoryBinaryReader, System.String, Int32)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager+<OnApplyOnLocalStateAsync>d__154.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.ServiceFabric.Replicator.DynamicStateManager+<OnApplyOnLocalStateAsync>d__154, Microsoft.ServiceFabric.Data.Impl, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<OnApplyOnLocalStateAsync>d__154 ByRef)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.OnApplyOnLocalStateAsync(Int64, Microsoft.ServiceFabric.Replicator.TransactionBase, System.Fabric.OperationData, System.Fabric.OperationData, Microsoft.ServiceFabric.Replicator.ApplyContext)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager+<OnApplyAsync>d__115.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.ServiceFabric.Replicator.DynamicStateManager+<OnApplyAsync>d__115, Microsoft.ServiceFabric.Data.Impl, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<OnApplyAsync>d__115 ByRef)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.OnApplyAsync(Int64, Microsoft.ServiceFabric.Replicator.TransactionBase, System.Fabric.OperationData, System.Fabric.OperationData, Microsoft.ServiceFabric.Replicator.ApplyContext, Int64)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager+<OnApplyAsync>d__114.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.ServiceFabric.Replicator.DynamicStateManager+<OnApplyAsync>d__114, Microsoft.ServiceFabric.Data.Impl, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<OnApplyAsync>d__114 ByRef)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.OnApplyAsync(Int64, Microsoft.ServiceFabric.Replicator.TransactionBase, System.Fabric.OperationData, System.Fabric.OperationData, Microsoft.ServiceFabric.Replicator.ApplyContext)
   at Microsoft.ServiceFabric.Replicator.OperationProcessor+<ApplyCallback>d__36.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.ServiceFabric.Replicator.OperationProcessor+<ApplyCallback>d__36, Microsoft.ServiceFabric.Data.Impl, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<ApplyCallback>d__36 ByRef)
   at Microsoft.ServiceFabric.Replicator.OperationProcessor.ApplyCallback(Microsoft.ServiceFabric.Replicator.LogRecord)
   at Microsoft.ServiceFabric.Replicator.OperationProcessor+<ProcessLoggedRecordAsync>d__32.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.ServiceFabric.Replicator.OperationProcessor+<ProcessLoggedRecordAsync>d__32, Microsoft.ServiceFabric.Data.Impl, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<ProcessLoggedRecordAsync>d__32 ByRef)
   at Microsoft.ServiceFabric.Replicator.OperationProcessor.ProcessLoggedRecordAsync(Microsoft.ServiceFabric.Replicator.LogRecord)
   at Microsoft.ServiceFabric.Replicator.LogRecordsDispatcher+<ProcessTransaction>d__21.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.ServiceFabric.Replicator.LogRecordsDispatcher+<ProcessTransaction>d__21, Microsoft.ServiceFabric.Data.Impl, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<ProcessTransaction>d__21 ByRef)
   at Microsoft.ServiceFabric.Replicator.LogRecordsDispatcher.ProcessTransaction(System.Collections.Generic.List`1<Microsoft.ServiceFabric.Replicator.TransactionLogRecord>)
   at Microsoft.ServiceFabric.Replicator.LogRecordsDispatcher+<SeparateTransactions>d__22.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.ServiceFabric.Replicator.LogRecordsDispatcher+<SeparateTransactions>d__22, Microsoft.ServiceFabric.Data.Impl, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<SeparateTransactions>d__22 ByRef)
   at Microsoft.ServiceFabric.Replicator.LogRecordsDispatcher.SeparateTransactions()
   at Microsoft.ServiceFabric.Replicator.LogRecordsDispatcher+<ProcessLoggedRecords>d__18.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.ServiceFabric.Replicator.LogRecordsDispatcher+<ProcessLoggedRecords>d__18, Microsoft.ServiceFabric.Data.Impl, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<ProcessLoggedRecords>d__18 ByRef)
   at Microsoft.ServiceFabric.Replicator.LogRecordsDispatcher.ProcessLoggedRecords()
   at Microsoft.ServiceFabric.Replicator.LogRecordsDispatcher+<StartProcessingLoggedRecords>d__23.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.ServiceFabric.Replicator.LogRecordsDispatcher+<StartProcessingLoggedRecords>d__23, Microsoft.ServiceFabric.Data.Impl, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<StartProcessingLoggedRecords>d__23 ByRef)
   at Microsoft.ServiceFabric.Replicator.LogRecordsDispatcher.StartProcessingLoggedRecords()
   at Microsoft.ServiceFabric.Replicator.LogRecordsDispatcher.DispatchLoggedRecords(Microsoft.ServiceFabric.Replicator.LoggedRecords)
   at Microsoft.ServiceFabric.Replicator.RecoveryManager+<PerformRecoveryAsync>d__31.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(Boolean)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(Boolean)
   at Microsoft.ServiceFabric.Replicator.LogRecords+<MoveNextAsync>d__19.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   at Microsoft.ServiceFabric.Replicator.LogRecord+<ReadNextRecordAsync>d__59.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.Threading.Tasks.VoidTaskResult)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.Threading.Tasks.VoidTaskResult)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.Threading.Tasks.Task`1<System.Threading.Tasks.VoidTaskResult>)
   at Microsoft.ServiceFabric.Replicator.Utility+<ReadAsync>d__61.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(Int32)
   at System.IO.FileStream.EndReadTask(System.IAsyncResult)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by Kassoul** [comment]
I have an error like you on backup from SF 7.2.... :-|

**Comment by anantshankar17** [comment]
Updated to now use SF dependencies with version 9.1 as the existing ones were ~6.5.
